name: 'Manually: Deploy'

on:
  workflow_dispatch:
    branches:
      - master
      - develop
    paths:
      - '/**'

jobs:
  build:
    name: Build and deploy Docker images
    runs-on: ubuntu-latest
    env:
      AWS_ECR_REPOSITORY: '321545123950.dkr.ecr.us-east-1.amazonaws.com'
    steps:
      - if: endsWith(github.ref, '/master')
        run: echo "BRANCH=master" >> $GITHUB_ENV

      - if: endsWith(github.ref, '/develop')
        run: echo "BRANCH=develop" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Change build script file permession
        run: chmod 777 scripts/build.sh

      - name: Build Docker image - URL Shortener API
        run: scripts/build.sh "url-shortener" ${{ github.sha }} $AWS_ECR_REPOSITORY $BRANCH false

      - name: Change deploy scrip file permession
        run: chmod 777 scripts/deploy.sh

      - name: Deploy - URL Shortener API
        run: scripts/deploy.sh "url-shortener-api" ${{ github.sha }} $AWS_ECR_REPOSITORY $BRANCH false



